{% set name = "opentelemetry-instrumentation-threading" %}
{% set version = "0.59b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ce5658730b697dcbc0e0d6d13643a69fd8aeb1b32fa8db3bade8ce114c7975f3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - opentelemetry-api >=1.12,<2
    - opentelemetry-instrumentation =={{ version }}
    - wrapt >=1.0.0,<2.0.0

# Tests disabled:
# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
test:
  imports:
    - opentelemetry.instrumentation.threading
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-threading
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: Thread context propagation support for OpenTelemetry
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library provides instrumentation for the threading module to ensure that the OpenTelemetry context is propagated across threads.
    It is important to note that this instrumentation does not produce any telemetry data on its own.
    It merely ensures that the context is correctly propagated when threads are used.

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
